
<?php $form->prepare() ?>
<div class="container-fluid">
    <?= $this->form()->openTag($form) ?>
        <div class="form-group input-group-sm">
            <?= $this->formRow($form->get('email')) ?>
        </div>
        <div class="form-group input-group-sm">
            <?= $this->formRow($form->get('password')) ?>
        </div>
        <button><?= $this->translate("Edit Account") ?></button>
    <?= $this->form()->closeTag($form)?>
</div>